apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
spec:
  serviceName: "thanos-store"
  replicas: 1
  selector:
    matchLabels:
      app: thanos
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos
        thanos-peer: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
      - name: thanos-store
        image: improbable/thanos:master
        env:
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-bucket
              key: s3_bucket
        - name: S3_ENDPOINT
          value: s3.us-east-1.amazonaws.com
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-bucket
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-bucket
              key: s3_secret_key
        - name: S3_SIGNATURE_VERSION2
          value: ''
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "store"
        - "--log.level=debug"
        - "--tsdb.path=/var/thanos/store"
        - "--cluster.peers=thanos-peers.$(POD_NAMESPACE).svc.cluster.local:10900"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store
  name: thanos-store
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-store
  selector:
    app: thanos-store
  sessionAffinity: None
  type: NodePort