apiVersion: "prometheus.robszumski.com/v1alpha1"
kind: "PrometheusReplica"
metadata:
  name: "example"
spec:
  configMap: prometheus-config
  highlyAvailable: true
  baseDomain: "example.com"
  metrics:
    retention: 24h
    blockDuration: 2m
  bucketSecret: s3-bucket